# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logRegApp', '0001_initial'),
        ('coursesApp', '0002_auto_20161016_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='user', to='logRegApp.User'),
        ),
    ]
