# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20161019_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CUser',
        ),
    ]
