# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_user_password'),
        ('courses', '0005_auto_20161020_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_user',
            field=models.ManyToManyField(default=None, to='loginreg.User'),
        ),
    ]
