# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modmodels', '0003_auto_20161015_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='0000000', editable=False, max_length=30),
        ),
    ]
