# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20161016_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
