# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20161016_2259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
